[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "false"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/post/tutkielmavinkit/"
  to = "/fi/post/viisivinkkia"
  status = 301
  force = false

[[redirects]]
  from = "/fi/post/tutkielmavinkit/"
  to = "/fi/post/viisivinkkia"
  status = 301
  force = false

[[redirects]]
  from = "/fi/blogi/tutkielmavinkit/"
  to = "/fi/post/viisivinkkia"
  status = 301
  force = false

[[redirects]]
  from = "/fi/blogi/omat-kotisivut/"
  to = "/fi/post/omat-kotisivut"
  status = 301
  force = false

[[redirects]]
  from = "/post/omat-kotisivut/"
  to = "/fi/post/omat-kotisivut"
  status = 301
  force = false

[[redirects]]
  from = "/fi/post/ajatusverkosto/"
  to = "/fi/post/zettelkasten"
  status = 301
  force = false

[[redirects]]
  from = "/fi/tag/muistiinpanot/"
  to = "/fi/tag/muistiinpanotekniikka"
  status = 301
  force = false

[[redirects]]
  from = "/fi/tag/tutkimusvinkit/"
  to = "/fi/category/tutkimusvinkit/"
  status = 301
  force = false

[[redirects]]
  from = "/tag/tutkimusvinkit/"
  to = "/fi/category/tutkimusvinkit/"
  status = 301
  force = false

[[redirects]]
  from = "/fi/tag/tutkimusviestinta/"
  to = "/fi/category/tutkimusviestintä/"
  status = 301
  force = false

[[redirects]]
  from = "/fi/tag/ajatusverkosto"
  to = "/fi/tag/zettelkasten"
  status = 301
  force = false